export const POST_CATEGORY = "POST_CATEGORY";
export const GET_INDIVIDUAL_CATAGORY = "GET_INDIVIDUAL_CATAGORY";
export const GET_ALL_CATAGORY = "GET_ALL_CATAGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";